name: Pull Request Checks

on:
  pull_request:
    branches:
      - master  # Triggers checks only on pull requests targeting master

jobs:
  checks:
    name: Run Checks
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu environment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Checks out your repository code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # You can specify your desired Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrades pip
          pip install flake8  # Installs flake8 for linting
          pip install pytest  # Installs pytest for testing
          # Add other dependencies you may need here

      - name: Run Lint Checks
        run: |
          flake8 .  # Runs linting on the code

      - name: Run Tests
        run: |
          pytest -v tests/  # Runs tests in the 'tests' directory with verbose output
