name: Pull Request Checks for Python

on:
  pull_request:
    branches:
      - master

jobs:
  python-checks:
    name: Python Checks
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Specify the Python version you want to use

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Linting (flake8)
      - name: Run Linting
        run: |
          pip install flake8
          flake8 .

      # Step 5: Run Tests (pytest)
      - name: Run Tests
        run: |
          pip install pytest
          pytest
