name: Pull Request Checks

on:
  pull_request:
    branches:
      - master  # Triggers checks only on pull requests targeting master

jobs:
  checks:
    name: Run Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Lint
        run: |
          echo "Running lint checks..."
          # Replace this with actual linting commands for your Python application
          pip install flake8
          flake8 .

      - name: Run Tests
        run: |
          echo "Running tests..."
          # Replace this with actual test commands
          pip install pytest
          pytest

      - name: Build Project
        run: |
          echo "Building the project..."
          # Replace this with actual build commands if needed
